# Generated by Django 4.2.30 on 2026-07-11 23:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='المسؤول')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget.costcenter', verbose_name='المركز الأب')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموازنة')),
                ('period', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], default='monthly', max_length=20, verbose_name='الفترة')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='الشهر')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ المخطط')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ الفعلي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('closed', 'مغلق')], default='draft', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.costcenter', verbose_name='مركز التكلفة')),
            ],
            options={
                'verbose_name': 'موازنة',
                'verbose_name_plural': 'الموازنات',
                'unique_together': {('account', 'cost_center', 'year', 'month')},
            },
        ),
    ]
