# Generated by Django 4.2.30 on 2026-07-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_alter_customer_credit_limit_and_more'),
        ('purchases', '0012_alter_supplier_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم أمر البيع')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('invoiced', 'مفوتر'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'أمر بيع',
                'verbose_name_plural': 'أوامر البيع',
                'ordering': ['-date', '-order_number'],
                'permissions': [('confirm_salesorder', 'تأكيد أمر بيع'), ('cancel_salesorder', 'إلغاء أمر بيع'), ('convert_salesorder', 'تحويل أمر بيع إلى فاتورة')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='سعر البيع')),
                ('invoiced_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الكمية المفوترة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales_orders.salesorder', verbose_name='أمر البيع')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند أمر بيع',
                'verbose_name_plural': 'بنود أمر البيع',
                'ordering': ['id'],
            },
        ),
    ]
