# Generated by Django 4.2.30 on 2026-07-11 23:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('symbol', models.CharField(max_length=10, verbose_name='الرمز')),
                ('exchange_rate_to_egp', models.DecimalField(decimal_places=6, default=1, max_digits=15, verbose_name='سعر الصرف إلى ج.م')),
                ('is_base', models.BooleanField(default=False, verbose_name='العملة الأساسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='سعر الصرف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='currency.currency', verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'سجل سعر الصرف',
                'verbose_name_plural': 'سجلات أسعار الصرف',
                'ordering': ['-date'],
            },
        ),
    ]
