# Generated by Django 4.2.30 on 2026-07-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_add_production_order_and_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETAConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='الافتراضي', max_length=100, verbose_name='اسم الإعداد')),
                ('environment', models.CharField(choices=[('sandbox', 'بيئة الاختبار (Sandbox)'), ('production', 'بيئة الإنتاج (Production)')], default='sandbox', max_length=20, verbose_name='بيئة التشغيل')),
                ('client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Secret')),
                ('certificate_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسار شهادة التوقيع')),
                ('certificate_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='كلمة سر الشهادة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعداد اتصال الضرائب',
                'verbose_name_plural': 'إعدادات اتصال الضرائب',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة الضريبية')),
                ('document_type', models.CharField(choices=[('i', 'فاتورة مبيعات (Issued)'), ('c', 'إشعار دائن (Credit)'), ('d', 'إشعار مدين (Debit)'), ('s', 'فاتورة مرتجع (Summary)')], default='i', max_length=1, verbose_name='نوع المستند')),
                ('eta_uuid', models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True, verbose_name='ETA UUID')),
                ('eta_submission_uuid', models.CharField(blank=True, max_length=36, null=True, verbose_name='Submission UUID')),
                ('eta_long_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='الرقم الطويل للتحقق')),
                ('eta_internal_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Internal ID')),
                ('eta_qr_code', models.TextField(blank=True, null=True, verbose_name='QR Code')),
                ('eta_pdf_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='رابط PDF')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('submitting', 'جارٍ الإرسال'), ('submitted', 'تم الإرسال'), ('valid', 'صالحة (مقبولة)'), ('invalid', 'غير صالحة (مرفوضة)'), ('failed', 'فشل الإرسال')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('total_sale_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='إجمالي المبيعات')),
                ('total_discount_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='إجمالي الخصم')),
                ('net_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الصافي')),
                ('total_vat_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='إجمالي ضريبة القيمة المضافة')),
                ('total_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي شامل الضريبة')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('submission_log', models.TextField(blank=True, null=True, verbose_name='سجل الإرسال')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='tax_invoices.etaconnection', verbose_name='إعداد الاتصال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_invoices', to='sales.salesinvoice', verbose_name='فاتورة المبيعات')),
            ],
            options={
                'verbose_name': 'فاتورة ضريبية',
                'verbose_name_plural': 'الفواتير الضريبية',
                'ordering': ['-created_at'],
            },
        ),
    ]
