# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('stock_adjustments', '0001_initial'), ('stock_adjustments', '0002_alter_stockadjustmentline_product')]

    dependencies = [
        ('purchases', '0002_purchaseinvoice_withholding_tax_amount_and_more'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0010_alter_supplier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الجرد')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('adjustment_type', models.CharField(choices=[('addition', 'إضافة'), ('deduction', 'خصم'), ('count', 'جرد فعلي')], max_length=15, verbose_name='نوع الجرد')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب التعديل')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد')], default='draft', max_length=15, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'تعديل مخزون',
                'verbose_name_plural': 'تعديلات المخزون',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المخزون الحالي')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock_adjustments.stockadjustment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
            ],
        ),
    ]
