# Generated by Django 4.2.30 on 2026-07-12 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasury', '0001_initial'),
        ('accounts', '0001_initial'),
        ('sales', '0002_salesinvoice_withholding_tax_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0003_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='رقم السند')),
                ('receipt_type', models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند دفع')], max_length=10, verbose_name='نوع السند')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('visa', 'فيزا/ماستر كارد')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشيك')),
                ('description', models.TextField(blank=True, null=True, verbose_name='البيان')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.bank', verbose_name='البنك')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='فاتورة مبيعات')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseinvoice', verbose_name='فاتورة مشتريات')),
                ('safe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.safe', verbose_name='الخزينة')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'سند قبض/دفع',
                'verbose_name_plural': 'سندات القبض والدفع',
                'ordering': ['-date'],
            },
        ),
    ]
