# Generated by Django 4.2.30 on 2026-07-11 22:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_id', models.CharField(max_length=50, unique=True, verbose_name='معرف الجهاز')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجهاز')),
                ('machine_type', models.CharField(choices=[('host', 'Host (جهاز رئيسي)'), ('client', 'Client (جهاز فرعي)'), ('standalone', 'مستقل (بدون ربط)')], default='standalone', max_length=20, verbose_name='نوع الجهاز')),
                ('api_key', models.CharField(max_length=64, verbose_name='مفتاح API')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'معلومات الجهاز',
                'verbose_name_plural': 'معلومات الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='تفعيل المزامنة التلقائية')),
                ('sync_interval_minutes', models.IntegerField(default=5, verbose_name='فترة المزامنة (دقائق)')),
                ('sync_on_startup', models.BooleanField(default=True, verbose_name='مزامنة عند التشغيل')),
                ('host_address', models.CharField(blank=True, max_length=200, verbose_name='عنوان Host')),
                ('host_port', models.IntegerField(default=8000, verbose_name='Port Host')),
                ('sync_key', models.CharField(blank=True, max_length=64, verbose_name='مفتاح الربط')),
            ],
            options={
                'verbose_name': 'إعدادات المزامنة',
                'verbose_name_plural': 'إعدادات المزامنة',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('push', 'إرسال'), ('pull', 'استلام'), ('full', 'مزامنة كاملة')], max_length=20, verbose_name='نوع المزامنة')),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'مكتملة'), ('failed', 'فشل'), ('partial', 'جزئية')], default='pending', max_length=20, verbose_name='الحالة')),
                ('records_sent', models.IntegerField(default=0, verbose_name='السجلات المرسلة')),
                ('records_received', models.IntegerField(default=0, verbose_name='السجلات المستلمة')),
                ('conflicts_found', models.IntegerField(default=0, verbose_name='التعارضات')),
                ('conflicts_resolved', models.IntegerField(default=0, verbose_name='التعارضات المحلولة')),
                ('sync_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات المزامنة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs_sent', to='sync.machineinfo', verbose_name='الجهاز المصدر')),
                ('target_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs_received', to='sync.machineinfo', verbose_name='الجهاز الهدف')),
            ],
            options={
                'verbose_name': 'سجل المزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-started_at'],
            },
        ),
    ]
