# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('common', '0001_initial'), ('common', '0002_userprofile')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_company_cogs_account_company_customer_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('message_type', models.CharField(default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('queued', 'في الطابور'), ('sent', 'مرسل'), ('delivered', 'تم التسليم'), ('read', 'مقروء'), ('failed', 'فشل'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.IntegerField(default=0, verbose_name='الأولوية')),
                ('max_retries', models.IntegerField(default=3, verbose_name='أقصى محاولات')),
                ('retry_count', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('error_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الخطأ')),
                ('meta_message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف رسالة ميتا')),
                ('webhook_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الويب هوك')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='مجدول في')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='أرسل في')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='سلم في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'طابور رسائل واتساب',
                'ordering': ['-priority', 'scheduled_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'scheduled_at'], name='common_what_status_c3cfd7_idx'), models.Index(fields=['phone', 'status'], name='common_what_phone_94d9d8_idx'), models.Index(fields=['created_at'], name='common_what_created_d16ecf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(choices=[('sales_invoice', 'فواتير المبيعات'), ('purchase_invoice', 'فواتير المشتريات'), ('receipt', 'سندات القبض'), ('payment', 'سندات الدفع'), ('sales_return', 'مرتجعات المبيعات'), ('purchase_return', 'مرتجعات المشتريات'), ('journal_entry', 'القيود المحاسبية')], max_length=30, verbose_name='النوع')),
                ('prefix', models.CharField(default='', max_length=10, verbose_name='البادئة')),
                ('year', models.IntegerField(default=2026, verbose_name='السنة')),
                ('last_number', models.IntegerField(default=0, verbose_name='آخر رقم')),
            ],
            options={
                'verbose_name': 'رقم تسلسلي',
                'verbose_name_plural': 'الأرقام التسلسلية',
                'unique_together': {('sequence_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_all_branches', models.BooleanField(default=False, verbose_name='صلاحية مشاهدة كل الفروع')),
                ('branch', models.ForeignKey(blank=True, help_text='يحدّ مشاهدة السجلات المرتبطة بفرع المستخدم فقط', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companybranch', verbose_name='الفرع')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
            },
        ),
    ]
