# Generated by Django 4.2.30 on 2026-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial_squashed_0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencenumber',
            name='sequence_type',
            field=models.CharField(choices=[('sales_invoice', 'فواتير المبيعات'), ('purchase_invoice', 'فواتير المشتريات'), ('receipt', 'سندات القبض'), ('payment', 'سندات الدفع'), ('sales_return', 'مرتجعات المبيعات'), ('purchase_return', 'مرتجعات المشتريات'), ('journal_entry', 'القيود المحاسبية'), ('purchase_order', 'أوامر الشراء'), ('sales_order', 'أوامر البيع'), ('goods_received', 'إيصالات استلام البضاعة'), ('requisition', 'طلبات الشراء')], max_length=30, verbose_name='النوع'),
        ),
    ]
