# Generated by Django 4.2.30 on 2026-07-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_sequencenumber_sequence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير'), ('accountant', 'محاسب'), ('warehouse_keeper', 'أمين مخزن'), ('sales', 'مبيعات'), ('purchasing', 'مشتريات'), ('viewer', 'مشاهدة فقط')], default='viewer', max_length=20, verbose_name='نوع الحساب الوظيفي'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_prices',
            field=models.BooleanField(default=True, verbose_name='صلاحية مشاهدة الأسعار والتكلفة'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='صالح من'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='صالح حتى'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='view_all_warehouses',
            field=models.BooleanField(default=False, verbose_name='صلاحية مشاهدة كل المخازن'),
        ),
    ]
