# Generated by Django 4.2 on 2026-07-11 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الأصل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأصل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الشراء')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='القيمة التخليصية')),
                ('useful_life_years', models.IntegerField(default=5, verbose_name='العمر الإنتاجي بالسنوات')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'القسط الثابت'), ('declining', 'القسط المتناقص')], default='straight_line', max_length=20, verbose_name='طريقة الإهلاك')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مجمع الإهلاك')),
                ('net_book_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='القيمة الدفترية الصافية')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='الموقع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('depreciated', 'مستهلك بالكامل'), ('disposed', 'تم التخلص منه')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.account', verbose_name='حساب الأصل')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ الإهلاك')),
                ('accumulated_after', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المجمع بعد الإهلاك')),
                ('months', models.IntegerField(default=1, verbose_name='عدد الأشهر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset', verbose_name='الأصل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'قيد إهلاك',
                'verbose_name_plural': 'قيود الإهلاك',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='نسبة الإهلاك السنوية %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='حساب الأصل')),
                ('depreciation_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depr_categories', to='accounts.account', verbose_name='حساب مجمع الإهلاك')),
            ],
            options={
                'verbose_name': 'تصنيف أصول',
                'verbose_name_plural': 'تصنيفات الأصول',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assetcategory', verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='asset',
            name='depr_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accum_depr', to='accounts.account', verbose_name='حساب مجمع الإهلاك'),
        ),
        migrations.AddField(
            model_name='asset',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='قيد الشراء'),
        ),
    ]
