# Generated by Django 4.2.30 on 2026-07-11 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='من تاريخ')),
                ('period_end', models.DateField(verbose_name='إلى تاريخ')),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد الدفتر')),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='رصيد البنك')),
                ('reconciled_diff', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='فرق التسوية')),
                ('status', models.CharField(choices=[('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.bank', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'جلسة تسوية بنكية',
                'verbose_name_plural': 'جلسات التسوية البنكية',
            },
        ),
        migrations.CreateModel(
            name='BankStatementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المدين')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الدائن')),
                ('status', models.CharField(choices=[('unmatched', 'غير مطابق'), ('matched', 'مطابق'), ('partial', 'مطابقة جزئية')], default='unmatched', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasury.bank', verbose_name='الحساب البنكي')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.banktransaction', verbose_name='المعاملة المطابقة')),
            ],
            options={
                'verbose_name': 'بند كشف حساب بنكي',
                'verbose_name_plural': 'بنود كشف الحساب البنكي',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
