# Generated by Django 4.2.30 on 2026-07-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('ai_analysis', '0001_initial'), ('ai_analysis', '0002_alter_errorlog_created_at_alter_errorlog_status')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=50, verbose_name='نوع الخطأ')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الشدة')),
                ('status', models.CharField(choices=[('detected', 'تم الكشف'), ('analyzing', 'قيد التحليل'), ('resolved', 'تم الحل'), ('ignored', 'تجاهل'), ('pending', 'بانتظار بيانات')], db_index=True, default='detected', max_length=20, verbose_name='الحالة')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('affected_account_code', models.CharField(blank=True, max_length=20, verbose_name='الحساب المتأثر')),
                ('affected_account_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الحساب')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('journal_entry_id', models.UUIDField(blank=True, null=True, verbose_name='معرف القيد')),
                ('raw_data', models.JSONField(default=dict, verbose_name='البيانات الأولية')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='تحليل الذكاء الاصطناعي')),
                ('suggested_solution', models.TextField(blank=True, verbose_name='الحل المقترح')),
                ('financial_impact', models.TextField(blank=True, verbose_name='التأثير المحاسبي')),
                ('required_documents', models.TextField(blank=True, verbose_name='المستندات المطلوبة')),
                ('detected_by', models.CharField(default='system', max_length=50, verbose_name='تم الكشف بواسطة')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحل')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل خطأ',
                'verbose_name_plural': 'سجلات الأخطاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_name', models.CharField(max_length=200, verbose_name='اسم النمط')),
                ('error_type', models.CharField(max_length=50, verbose_name='نوع الخطأ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('detection_rule', models.JSONField(verbose_name='قاعدة الكشف')),
                ('example', models.TextField(blank=True, verbose_name='مثال')),
                ('suggested_fix', models.TextField(verbose_name='الحل المقترح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('occurrence_count', models.IntegerField(default=0, verbose_name='عدد التكرار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نمط خطأ',
                'verbose_name_plural': 'أنماط الأخطاء',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(1, 'الأولى'), (2, 'الثانية'), (3, 'الثالثة')], verbose_name='الأولوية')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('steps', models.JSONField(default=list, verbose_name='الخطوات')),
                ('financial_impact', models.TextField(verbose_name='التأثير المحاسبي')),
                ('risk_level', models.CharField(default='low', max_length=20, verbose_name='مستوى المخاطرة')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يحتاج موافقة')),
                ('applied', models.BooleanField(default=False, verbose_name='تم التطبيق')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التطبيق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التطبيق بواسطة')),
                ('error_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='ai_analysis.errorlog', verbose_name='الخطأ')),
            ],
            options={
                'verbose_name': 'حل مقترح',
                'verbose_name_plural': 'حلول مقترحة',
                'ordering': ['priority'],
            },
        ),
    ]
