# Generated by Django 4.2.30 on 2026-07-14 10:02

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid


def populate_category_codes(apps, schema_editor):
    ProductCategory = apps.get_model('purchases', 'ProductCategory')
    existing = set(
        ProductCategory.objects.filter(code__isnull=False).values_list('code', flat=True)
    )
    counter = 1
    for category in ProductCategory.objects.filter(code__isnull=True).order_by('id'):
        while True:
            candidate = 'CAT-%04d' % counter
            counter += 1
            if candidate not in existing:
                break
        category.code = candidate
        existing.add(candidate)
        category.save(update_fields=['code'])

class Migration(migrations.Migration):

    replaces = [('purchases', '0001_initial'), ('purchases', '0002_purchaseinvoice_withholding_tax_amount_and_more'), ('purchases', '0003_product_barcode'), ('purchases', '0004_alter_productcategory_options_productcategory_code_and_more'), ('purchases', '0005_purchaseinvoice_file_number'), ('purchases', '0006_alter_product_current_stock_and_more'), ('purchases', '0007_purchaseinvoice_pi_supplier_date_idx_and_more'), ('purchases', '0008_alter_purchaseinvoice_discount_amount_and_more'), ('purchases', '0009_alter_purchaseinvoice_discount_amount_and_more'), ('purchases', '0010_alter_supplier_options'), ('purchases', '0011_alter_supplier_credit_limit_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المنتج')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('unit', models.CharField(default='قطعة', max_length=50, verbose_name='وحدة القياس')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر الشراء')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المخزون الحالي')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للمخزون')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='كود التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف منتج',
                'verbose_name_plural': 'تصنيفات المنتجات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('check', 'شيك'), ('transfer', 'تحويل بنكي')], default='credit', max_length=20, verbose_name='طريقة الدفع')),
                ('is_tax_invoice', models.BooleanField(default=True, verbose_name='فاتورة مؤثرة في الضرائب')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ قبل الضريبة')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ضريبة القيمة المضافة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الخصم')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ المتبقي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'فاتورة مشتريات',
                'verbose_name_plural': 'فواتير المشتريات',
                'ordering': ['-date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المورد')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('supplier_type', models.CharField(choices=[('company', 'شركة'), ('individual', 'فرد')], default='company', max_length=20, verbose_name='نوع المورد')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, null=True, verbose_name='سجل تجاري')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='التليفون')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='المحمول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='حد الائتمان')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseinvoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند فاتورة مشتريات',
                'verbose_name_plural': 'بنود فواتير المشتريات',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.productcategory', verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ الخصم والتحصيل'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='withholding_tax_type',
            field=models.IntegerField(choices=[(0, 'بدون'), (1, '1% - شركات'), (3, '3% - جهات حكومية'), (5, '5% - مقاولات')], default=0, verbose_name='نسبة الخصم والتحصيل'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الخصم على الفاتورة'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الباركود'),
        ),
        migrations.RunPython(
            populate_category_codes,
            django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='كود التصنيف'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='purchases.productcategory', verbose_name='التصنيف الأعلى'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الوحدة')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوحدة')),
                ('symbol', models.CharField(blank=True, max_length=20, null=True, verbose_name='رمز الوحدة')),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1, max_digits=15, verbose_name='معامل التحويل للوحدة الأساسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='purchases.unitofmeasure', verbose_name='الوحدة الأساسية')),
            ],
            options={
                'verbose_name': 'وحدة قياس',
                'verbose_name_plural': 'وحدات القياس',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enforce_unit', models.BooleanField(default=False, verbose_name='إلزام تحديد وحدة القياس')),
                ('enforce_category', models.BooleanField(default=False, verbose_name='إلزام تحديد التصنيف')),
                ('allow_decimal_quantity', models.BooleanField(default=True, verbose_name='السماح بكميات عشرية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchases.productcategory', verbose_name='التصنيف الافتراضي')),
                ('default_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchases.unitofmeasure', verbose_name='وحدة القياس الافتراضية')),
            ],
            options={
                'verbose_name': 'إعدادات الكتالوج',
                'verbose_name_plural': 'إعدادات الكتالوج',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='purchases.unitofmeasure', verbose_name='وحدة القياس'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='file_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الملف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='المخزون الحالي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الحد الأدنى للمخزون'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الخصم على الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='ضريبة القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='مبلغ الخصم والتحصيل'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='سعر الوحدة'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['supplier', '-date'], name='pi_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['date', 'is_posted'], name='pi_date_posted_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_number'], name='pi_number_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['file_number'], name='pi_file_number_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['payment_method', '-date'], name='pi_paymethod_date_idx'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='الخصم على الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('check', 'شيك'), ('transfer', 'تحويل بنكي')], default='credit', max_length=20, validators=[common.validators.validate_payment_method], verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='ضريبة القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='مبلغ الخصم والتحصيل'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='withholding_tax_type',
            field=models.IntegerField(choices=[(0, 'بدون'), (1, '1% - شركات'), (3, '3% - جهات حكومية'), (5, '5% - مقاولات')], default=0, validators=[common.validators.validate_withholding_tax_type], verbose_name='نسبة الخصم والتحصيل'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[common.validators.validate_positive_decimal], verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='سعر الوحدة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الخصم على الفاتورة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='ضريبة القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='مبلغ الخصم والتحصيل'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي'),
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['code'], 'permissions': [('view_supplier_list', 'عرض قائمة الموردين'), ('export_supplier', 'تصدير بيانات الموردين')], 'verbose_name': 'مورد', 'verbose_name_plural': 'الموردين'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
    ]
