# Generated by Django 4.2.30 on 2026-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial_squashed_0011_alter_supplier_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='current_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الرصيد الحالي'),
        ),
    ]
