# Generated by Django 4.2.30 on 2026-07-14 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0012_alter_supplier_credit_limit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': [('approve_purchaseinvoice', 'اعتماد فاتورة مشتريات'), ('print_purchaseinvoice', 'طباعة فاتورة مشتريات'), ('export_purchaseinvoice', 'تصدير فواتير المشتريات')], 'verbose_name': 'فاتورة مشتريات', 'verbose_name_plural': 'فواتير المشتريات'},
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchases', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة'),
        ),
    ]
