# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('hr', '0001_initial'), ('hr', '0002_alter_employee_options'), ('hr', '0003_alter_employee_status')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم القسم')),
                ('manager', models.CharField(blank=True, max_length=200, null=True, verbose_name='مدير القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الموظف')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('marital_status', models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], default='single', max_length=20, verbose_name='الحالة الاجتماعية')),
                ('position', models.CharField(max_length=200, verbose_name='الوظيفة')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='التليفون')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='المحمول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('social_insurance_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التأمين الاجتماعي')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب البنكي')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('terminated', 'تم الفصل')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المحاسبي')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['employee_number'],
                'permissions': [('approve_salary', 'اعتماد راتب'), ('print_salary', 'طباعة كشف راتب'), ('export_salary', 'تصدير الرواتب')],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب الأساسي')),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='البدلات')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='العمل الإضافي')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصومات')),
                ('social_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='التأمين الاجتماعي')),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ضريبة الدخل')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='صافي الراتب')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='hr.employee', verbose_name='الموظف')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'راتب',
                'verbose_name_plural': 'الرواتب',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('leave', 'إجازة'), ('sick', 'مرضي')], default='present', max_length=20, verbose_name='الحالة')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات العمل الإضافي')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
