# Generated by Django 4.2.30 on 2026-07-19 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial_squashed_0003_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نوع الإجازة')),
                ('days_per_year', models.IntegerField(default=0, verbose_name='الأيام سنوياً')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('days', models.IntegerField(verbose_name='عدد الأيام')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمدة'), ('rejected', 'مرفوضة'), ('cancelled', 'ملغاة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='hr.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.leavetype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('contract_type', models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'مؤقت'), ('part_time', 'دوام جزئي'), ('internship', 'تدريب'), ('freelance', 'عمل حر')], default='permanent', max_length=20, verbose_name='نوع العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الراتب')),
                ('probation_period_months', models.IntegerField(default=3, verbose_name='فترة التجربة (أشهر)')),
                ('annual_leave_days', models.IntegerField(default=21, verbose_name='أيام الإجازة السنوية')),
                ('notice_period_days', models.IntegerField(default=30, verbose_name='أيام فترة الإشعار')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('terminated', 'ملغي')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_contracts_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'عقد عمل',
                'verbose_name_plural': 'عقود العمل',
                'ordering': ['-start_date'],
            },
        ),
    ]
