# Generated by Django 4.2.30 on 2026-07-14 10:02

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_journalentry_file_number'), ('accounts', '0003_alter_account_current_balance_and_more'), ('accounts', '0004_alter_account_current_balance_and_more'), ('accounts', '0005_alter_account_current_balance_and_more'), ('accounts', '0006_journalentryline_jel_acct_entry_idx_and_more'), ('accounts', '0007_alter_journalentryline_options_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم النوع')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود النوع')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق الملكية'), ('revenue', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع حساب',
                'verbose_name_plural': 'أنواع الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القيد')),
                ('entry_type', models.CharField(choices=[('general', 'قيد عام'), ('purchase', 'قيد مشتريات'), ('sale', 'قيد مبيعات'), ('receipt', 'قيد تحصيل'), ('payment', 'قيد دفع'), ('depreciation', 'قيد إهلاك'), ('payroll', 'قيد رواتب'), ('adjustment', 'قيد تسوية')], max_length=20, verbose_name='نوع القيد')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('description', models.TextField(verbose_name='البيان')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='المرجع')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحل')),
                ('is_reversed', models.BooleanField(default=False, verbose_name='معكوس')),
                ('total_debit', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='إجمالي الدائن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('file_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الملف')),
            ],
            options={
                'verbose_name': 'قيد محاسبي',
                'verbose_name_plural': 'القيود المحاسبية',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الحساب')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('opening_balance', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='الرصيد الحالي')),
                ('is_bank', models.BooleanField(default=False, verbose_name='حساب بنكي')),
                ('is_safe', models.BooleanField(default=False, verbose_name='حساب خزينة')),
                ('tax_account', models.BooleanField(default=False, verbose_name='حساب ضريبي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounts.accounttype', verbose_name='نوع الحساب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='دائن')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'بند القيد',
                'verbose_name_plural': 'بنود القيود',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'is_active'], name='acc_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent', 'is_active'], name='acc_parent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entry_type', '-date'], name='je_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['is_posted', '-date'], name='je_posted_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference'], name='je_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['created_by', '-date'], name='je_user_date_idx'),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الرصيد الافتتاحي'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='credit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='دائن'),
        ),
        migrations.AlterField(
            model_name='journalentryline',
            name='debit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='مدين'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account', 'journal_entry'], name='jel_acct_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='jel_account_idx'),
        ),
        migrations.AlterModelOptions(
            name='journalentryline',
            options={'ordering': ['journal_entry', 'id'], 'verbose_name': 'بند القيد', 'verbose_name_plural': 'بنود القيود'},
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='jel_debit_or_credit_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(check=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='jel_non_negative_amounts'),
        ),
    ]
