# Generated by Django 4.2.30 on 2026-07-11 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=False, verbose_name='تفعيل النسخ التلقائي')),
                ('backup_interval_hours', models.IntegerField(default=24, verbose_name='فترة النسخ (ساعات)')),
                ('max_backups', models.IntegerField(default=30, verbose_name='الحد الأقصى للنسخ')),
                ('backup_database', models.BooleanField(default=True, verbose_name='نسخ قاعدة البيانات')),
                ('backup_media', models.BooleanField(default=True, verbose_name='نسخ الملفات المرفقة')),
                ('backup_source', models.BooleanField(default=True, verbose_name='نسخ الملفات المصدرية')),
            ],
            options={
                'verbose_name': 'إعدادات النسخ الاحتياطي',
                'verbose_name_plural': 'إعدادات النسخ الاحتياطي',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم النسخة')),
                ('backup_type', models.CharField(choices=[('data', 'DB + Media (بيانات)'), ('full', 'نسخة كاملة (الكل)'), ('json', 'تصدير JSON')], max_length=20, verbose_name='النوع')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='الحجم (بايت)')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('completed', 'مكتملة'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
    ]
