# Generated by Django 4.2.30 on 2026-07-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(verbose_name='مبرر الطلب')),
                ('reset_scope', models.CharField(choices=[('business_data', 'بيانات المعاملات فقط (مع الحفاظ على المستخدمين والإعدادات)'), ('full', 'استعادة كاملة (مسح كل البيانات عدا حسابات الدخول)')], default='business_data', max_length=20, verbose_name='نطاق الاستعادة')),
                ('status', models.CharField(choices=[('pending_approval', 'بانتظار الاعتماد'), ('approved', 'معتمد (بانتظار التنفيذ)'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى'), ('expired', 'منتهي الصلاحية'), ('executing', 'قيد التنفيذ'), ('completed', 'اكتمل'), ('failed', 'فشل التنفيذ')], db_index=True, default='pending_approval', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الطالب')),
                ('requester_user_agent', models.CharField(blank=True, max_length=500, verbose_name='جهاز الطالب')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت المراجعة')),
                ('review_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP المعتمِد')),
                ('review_user_agent', models.CharField(blank=True, max_length=500, verbose_name='جهاز المعتمِد')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجعة')),
                ('approval_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية الاعتماد')),
                ('execution_token_hash', models.CharField(blank=True, max_length=64, verbose_name='تجزئة رمز التنفيذ')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التنفيذ')),
                ('execution_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP المنفّذ')),
                ('execution_user_agent', models.CharField(blank=True, max_length=500, verbose_name='جهاز المنفّذ')),
                ('result_notes', models.TextField(blank=True, verbose_name='نتيجة التنفيذ')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_reset_executions', to=settings.AUTH_USER_MODEL, verbose_name='المنفّذ')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_reset_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المعتمِد')),
                ('safety_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backups.backup', verbose_name='النسخة الاحتياطية الأمنية')),
            ],
            options={
                'verbose_name': 'طلب استعادة ضبط المصنع',
                'verbose_name_plural': 'طلبات استعادة ضبط المصنع',
                'ordering': ['-requested_at'],
                'permissions': [('execute_factory_reset', 'تنفيذ استعادة ضبط المصنع')],
            },
        ),
    ]
