# Generated by Django 4.2 on 2026-07-11 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم التقرير')),
                ('report_type', models.CharField(choices=[('income_statement', 'قائمة الدخل'), ('balance_sheet', 'الميزانية العمومية'), ('trial_balance', 'ميزان المراجعة'), ('vat_return', 'إقرار ضريبة القيمة المضافة'), ('withholding_tax', 'ضريبة الخصم والتحصيل'), ('supplier_report', 'تقرير الموردين'), ('customer_report', 'تقرير العملاء'), ('profit_margin', 'تقرير نسب الربح'), ('asset_schedule', 'جدول الأصول والإهلاك'), ('payroll_report', 'تقرير الرواتب')], max_length=30, verbose_name='نوع التقرير')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب تقرير',
                'verbose_name_plural': 'قوالب التقارير',
                'ordering': ['name'],
            },
        ),
    ]
