# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('documents', '0001_initial'), ('documents', '0002_alter_document_reference_amount_and_more')]

    dependencies = [
        ('hr', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المستند')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان المستند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('reference_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ المرجعي')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع الخارجي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المحاسبي المرتبط')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول التنفيذ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-date', '-document_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود النوع')),
                ('name', models.CharField(max_length=200, verbose_name='اسم نوع المستند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('prefix', models.CharField(max_length=10, verbose_name='بادئة الرقم')),
                ('next_number', models.IntegerField(default=1, verbose_name='التالي رقم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع مستند',
                'verbose_name_plural': 'أنواع المستندات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم القالب')),
                ('content', models.TextField(verbose_name='محتوى القالب')),
                ('is_default', models.BooleanField(default=False, verbose_name='القالب الافتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='documents.documenttype', verbose_name='نوع المستند')),
            ],
            options={
                'verbose_name': 'قالب مستند',
                'verbose_name_plural': 'قوالب المستندات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('submit', 'تقديم'), ('review', 'مراجعة'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('archive', 'أرشفة'), ('cancel', 'إلغاء'), ('comment', 'تعليق')], max_length=20, verbose_name='الإجراء')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='من حالة')),
                ('to_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='إلى حالة')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='documents.document', verbose_name='المستند')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نفّذ الإجراء')),
            ],
            options={
                'verbose_name': 'تدفق مستند',
                'verbose_name_plural': 'حركات المستندات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/attachments/%Y/%m/', verbose_name='الملف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الملف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document', verbose_name='المستند')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق مستند',
                'verbose_name_plural': 'مرفقات المستندات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='نوع المستند'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reference_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, verbose_name='المبلغ المرجعي'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة'),
        ),
    ]
