# Generated by Django 4.2.30 on 2026-07-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_received', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='الكمية المستلمة')),
                ('unit_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='سعر الوحدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'بند استلام بضاعة',
                'verbose_name_plural': 'بنود استلام البضاعة',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grn_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم إيصال الاستلام')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'إيصال استلام بضاعة',
                'verbose_name_plural': 'إيصالات استلام البضاعة',
                'ordering': ['-date', '-grn_number'],
                'permissions': [('confirm_goodsreceivednote', 'تأكيد إيصال استلام'), ('convert_goodsreceivednote', 'تحويل إيصال استلام إلى فاتورة')],
            },
        ),
    ]
