# Generated by Django 4.2.30 on 2026-07-14 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0012_alter_supplier_credit_limit_and_more'),
        ('goods_received', '0001_initial'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_received_notes', to='purchase_orders.purchaseorder', verbose_name='أمر الشراء'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='goodsreceivedline',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='goods_received.goodsreceivednote', verbose_name='إيصال الاستلام'),
        ),
        migrations.AddField(
            model_name='goodsreceivedline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='goodsreceivedline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_received_lines', to='purchase_orders.purchaseorderline', verbose_name='بند أمر الشراء'),
        ),
    ]
