# Generated by Django 4.2.30 on 2026-07-14 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial_squashed_0003_stockmovement_sm_wh_date_idx_and_more'),
        ('goods_received', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='المستودع'),
        ),
        migrations.AlterField(
            model_name='goodsreceivedline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='الكمية المستلمة'),
        ),
        migrations.AlterField(
            model_name='goodsreceivedline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='سعر الوحدة'),
        ),
    ]
