# Generated by Django 4.2.30 on 2026-07-13 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchases", "0001_initial_squashed_0011_alter_supplier_credit_limit_and_more"),
        ("sales", "0001_initial_squashed_0010_alter_customer_credit_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial_squashed_0007_alter_journalentryline_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConcreteMixDesign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود الخلطة"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الخلطة")),
                (
                    "strength_class",
                    models.CharField(
                        help_text="مثال: C25/30, C30/37",
                        max_length=50,
                        verbose_name="فئة القوة",
                    ),
                ),
                (
                    "slump_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="قيمة الانهيار بالسنتيمتر",
                        max_digits=6,
                        verbose_name="الانهيار (سم)",
                    ),
                ),
                (
                    "max_aggregate_mm",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=6,
                        verbose_name="حجم أقصى للركام (مم)",
                    ),
                ),
                (
                    "water_cement_ratio",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="نسبة وسطرة الماء للأسمنت",
                        max_digits=5,
                        verbose_name="نسبة الماء/الأسمنت",
                    ),
                ),
                (
                    "target_strength_mpa",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="قوة الضغط المطلوبة بعد 28 يوم",
                        max_digits=8,
                        verbose_name="قوة الهدف (ميجاباسكال)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "cost_per_m3",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        verbose_name="التكلفة للمتر المكعب",
                    ),
                ),
                (
                    "selling_price_per_m3",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        verbose_name="سعر البيع للمتر المكعب",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
            ],
            options={
                "verbose_name": "تصميم خلطة الخرسانة",
                "verbose_name_plural": "تصاميم خلطات الخرسانة",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CustomerRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الطلب"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=300, verbose_name="اسم المشروع"),
                ),
                ("site_address", models.TextField(verbose_name="عنوان الموقع")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="جهة الاتصال"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="هاتف الاتصال"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جديد"),
                            ("confirmed", "مؤكد"),
                            ("in_production", "قيد الإنتاج"),
                            ("delivered", "تم التسليم"),
                            ("cancelled", "ملغي"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.customer",
                        verbose_name="العميل",
                    ),
                ),
            ],
            options={
                "verbose_name": "طلب عميل",
                "verbose_name_plural": "طلبات العملاء",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم اللوحة"
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(max_length=200, verbose_name="اسم السائق"),
                ),
                (
                    "driver_phone",
                    models.CharField(max_length=50, verbose_name="هاتف السائق"),
                ),
                (
                    "capacity_m3",
                    models.PositiveIntegerField(
                        choices=[
                            (6, "6 م³"),
                            (7, "7 م³"),
                            (8, "8 م³"),
                            (9, "9 م³"),
                            (10, "10 م³"),
                            (12, "12 م³"),
                        ],
                        default=8,
                        verbose_name="السعة (م³)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "متاحة"),
                            ("on_route", "في الطريق"),
                            ("delivering", "قيد التسليم"),
                            ("returning", "عائدة"),
                            ("maintenance", "صيانة"),
                            ("out_of_service", "خارج الخدمة"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "current_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="خط العرض الحالي",
                    ),
                ),
                (
                    "current_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="خط الطول الحالي",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
            ],
            options={
                "verbose_name": "شاحنة",
                "verbose_name_plural": "الشاحنات",
                "ordering": ["plate_number"],
            },
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم أمر الإنتاج"
                    ),
                ),
                (
                    "quantity_m3",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="الكمية المطلوبة (م³)",
                    ),
                ),
                (
                    "quantity_delivered",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="الكمية المسلمة (م³)",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "عادي"),
                            ("urgent", "عاجل"),
                            ("very_urgent", "عاجل جداً"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة"),
                            ("scheduled", "مجدول"),
                            ("in_progress", "قيد التنفيذ"),
                            ("completed", "مكتمل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الجدولة"
                    ),
                ),
                (
                    "scheduled_time_from",
                    models.TimeField(blank=True, null=True, verbose_name="من الساعة"),
                ),
                (
                    "scheduled_time_to",
                    models.TimeField(blank=True, null=True, verbose_name="إلى الساعة"),
                ),
                (
                    "pump_required",
                    models.BooleanField(default=False, verbose_name="يتطلب مضخة"),
                ),
                (
                    "pump_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=12,
                        verbose_name="تكلفة المضخة",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(blank=True, verbose_name="متطلبات خاصة"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=15,
                        verbose_name="سعر الوحدة",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=18,
                        verbose_name="الإجمالي",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "customer_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_orders",
                        to="concrete_production.customerrequest",
                        verbose_name="طلب العميل",
                    ),
                ),
                (
                    "mix_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="concrete_production.concretemixdesign",
                        verbose_name="تصميم الخلطة",
                    ),
                ),
            ],
            options={
                "verbose_name": "أمر إنتاج",
                "verbose_name_plural": "أوامر الإنتاج",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("materials", "مواد أولية"),
                            ("labor", "أجور عمال"),
                            ("transport", "نقل"),
                            ("fuel", "وقود"),
                            ("maintenance", "صيانة"),
                            ("equipment", "معدات"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع التكلفة",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6, max_digits=15, verbose_name="المبلغ"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="الوصف"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="التاريخ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.journalentry",
                        verbose_name="القيد المحاسبي",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="concrete_production.productionorder",
                        verbose_name="أمر الإنتاج",
                    ),
                ),
            ],
            options={
                "verbose_name": "تكلفة إنتاج",
                "verbose_name_plural": "تكاليف الإنتاج",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الدفعة"
                    ),
                ),
                (
                    "quantity_m3",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="الكمية (م³)"
                    ),
                ),
                (
                    "actual_quantity_m3",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="الكمية الفعلية (م³)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "في الطابور"),
                            ("mixing", "جاري الخلط"),
                            ("loading", "جاري التحميل"),
                            ("in_transit", "في الطريق"),
                            ("pouring", "جاري الصب"),
                            ("completed", "مكتمل"),
                            ("returned", "مرتجع"),
                            ("cancelled", "ملغي"),
                        ],
                        default="queued",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "mixing_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الخلط"
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت المغادرة"
                    ),
                ),
                (
                    "arrival_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الوصول"
                    ),
                ),
                (
                    "pouring_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بداية الصب"
                    ),
                ),
                (
                    "pouring_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="نهاية الصب"
                    ),
                ),
                (
                    "returned_quantity_m3",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="الكمية المرتجعة (م³)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="concrete_production.productionorder",
                        verbose_name="أمر الإنتاج",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="concrete_production.truck",
                        verbose_name="الشاحنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة إنتاجية",
                "verbose_name_plural": "الدفعات الإنتاجية",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MixComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("cement", "أسمنت"),
                            ("fine_aggregate", "ركام ناعم (رمل)"),
                            ("coarse_aggregate", "ركام خشن (كحلاوي)"),
                            ("water", "ماء"),
                            ("ad_additive", "مدھات كيميائية"),
                            ("fly_ash", "رماد طائر"),
                            ("slag", "خامل محطم"),
                            ("fiber", "ألياف"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع المكون",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المكون")),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="الكمية (كجم/م³)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
                ),
                (
                    "mix_design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="concrete_production.concretemixdesign",
                        verbose_name="تصميم الخلطة",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="المنتج في نظام المخزون المقابل لهذا المكون",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.product",
                        verbose_name="المنتج المقابل",
                    ),
                ),
            ],
            options={
                "verbose_name": "مكون الخلطة",
                "verbose_name_plural": "مكونات الخلطة",
                "ordering": ["order", "component_type"],
            },
        ),
        migrations.CreateModel(
            name="DeliverySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("delivery_date", models.DateField(verbose_name="تاريخ التسليم")),
                ("time_slot_from", models.TimeField(verbose_name="من الساعة")),
                ("time_slot_to", models.TimeField(verbose_name="إلى الساعة")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "مجدول"),
                            ("confirmed", "مؤكد"),
                            ("en_route", "في الطريق"),
                            ("delivered", "تم التسليم"),
                            ("cancelled", "ملغي"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(default=1, verbose_name="الترتيب"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="concrete_production.productionbatch",
                        verbose_name="الدفعة",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_schedules",
                        to="concrete_production.productionorder",
                        verbose_name="أمر الإنتاج",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="concrete_production.truck",
                        verbose_name="الشاحنة",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول تسليم",
                "verbose_name_plural": "جداول التسليم",
                "ordering": ["delivery_date", "time_slot_from"],
            },
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(fields=["status"], name="concrete_pr_status_689894_idx"),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["scheduled_date"], name="concrete_pr_schedul_cdf835_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionorder",
            index=models.Index(
                fields=["priority"], name="concrete_pr_priorit_0a30ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(fields=["status"], name="concrete_pr_status_c79b0b_idx"),
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(
                fields=["-created_at"], name="concrete_pr_created_60421b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mixcomponent",
            unique_together={("mix_design", "component_type", "name")},
        ),
        migrations.AddIndex(
            model_name="deliveryschedule",
            index=models.Index(
                fields=["delivery_date"], name="concrete_pr_deliver_4fa0c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryschedule",
            index=models.Index(fields=["status"], name="concrete_pr_status_1007a5_idx"),
        ),
        migrations.AddIndex(
            model_name="customerrequest",
            index=models.Index(fields=["status"], name="concrete_pr_status_e158e1_idx"),
        ),
        migrations.AddIndex(
            model_name="customerrequest",
            index=models.Index(
                fields=["customer"], name="concrete_pr_custome_78a8d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerrequest",
            index=models.Index(
                fields=["-created_at"], name="concrete_pr_created_159c62_idx"
            ),
        ),
    ]
