# Generated by Django 4.2.30 on 2026-07-13 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("purchases", "0001_initial_squashed_0011_alter_supplier_credit_limit_and_more"),
        ("concrete_production", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Silo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم السيلة")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="كود السيلة"
                    ),
                ),
                (
                    "capacity_tons",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="السعة الطاقة (طن)",
                    ),
                ),
                (
                    "current_stock_tons",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="المخزون الحالي (طن)",
                    ),
                ),
                (
                    "minimum_order_tons",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب (طن)",
                    ),
                ),
                (
                    "critical_level_tons",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="الحد الحرج (طن)",
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=300, verbose_name="الموقع"),
                ),
                (
                    "cement_type",
                    models.CharField(
                        blank=True,
                        help_text="مثال: CEM I, CEM II",
                        max_length=100,
                        verbose_name="نوع الاسمنت",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.supplier",
                        verbose_name="المورد الأساسي",
                    ),
                ),
            ],
            options={
                "verbose_name": "سيلة اسمنت",
                "verbose_name_plural": "السيلو",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SiloTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("in", "توريد"),
                            ("out", "استهلاك"),
                            ("adjustment", "تسوية"),
                        ],
                        max_length=20,
                        verbose_name="نوع الحركة",
                    ),
                ),
                (
                    "quantity_tons",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="الكمية (طن)"
                    ),
                ),
                (
                    "previous_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="المخزون السابق (طن)",
                    ),
                ),
                (
                    "new_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="المخزون الجديد (طن)",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="رقم المرجع"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="التاريخ"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "production_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="concrete_production.productionorder",
                        verbose_name="أمر الإنتاج المرتبط",
                    ),
                ),
                (
                    "silo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="concrete_production.silo",
                        verbose_name="السيلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "حركة سيلة",
                "verbose_name_plural": "حركات السيلو",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["silo"], name="concrete_pr_silo_id_302967_idx"
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="concrete_pr_transac_c9fe8a_idx",
                    ),
                    models.Index(fields=["-date"], name="concrete_pr_date_0f0e32_idx"),
                ],
            },
        ),
    ]
