# Generated by Django 4.2.30 on 2026-07-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concrete_production", "0002_add_silo_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("approve_productionorder", "اعتماد أمر إنتاج"),
                    ("print_productionorder", "طباعة أمر إنتاج"),
                ],
                "verbose_name": "أمر إنتاج",
                "verbose_name_plural": "أوامر الإنتاج",
            },
        ),
    ]
