# Generated by Django 4.2.30 on 2026-07-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial_squashed_0010_alter_customer_credit_limit_and_more"),
        ("purchases", "0001_initial_squashed_0011_alter_supplier_credit_limit_and_more"),
        ("concrete_production", "0003_alter_productionorder_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="concretemixdesign",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="يُستخدم عند إنشاء فاتورة مبيعات تلقائية لتسليم الخرسانة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="purchases.product",
                verbose_name="المنتج المقابل في المخزون",
            ),
        ),
        migrations.AddField(
            model_name="productionorder",
            name="sales_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="تُنشأ تلقائياً عند اكتمال تسليم الخرسانة",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_orders",
                to="sales.salesinvoice",
                verbose_name="فاتورة المبيعات المولّدة",
            ),
        ),
    ]
