# Generated by Django 4.2.30 on 2026-07-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_cogs_account_company_customer_account_and_more"),
        ("concrete_production", "0004_concretemixdesign_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="يُستخدم للصلاحيات على مستوى الكائن",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="company.companybranch",
                verbose_name="الفرع",
            ),
        ),
    ]
