# Generated by Django 4.2.30 on 2026-07-14 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
        ('purchases', '0013_alter_purchaseinvoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم طلب الشراء')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('need_by_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحاجة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('ordered', 'تم الطلب'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_requested', to=settings.AUTH_USER_MODEL, verbose_name='طالب الشراء')),
            ],
            options={
                'verbose_name': 'طلب شراء',
                'verbose_name_plural': 'طلبات الشراء',
                'ordering': ['-date', '-number'],
                'permissions': [('approve_requisition', 'اعتماد طلب شراء'), ('reject_requisition', 'رفض طلب شراء'), ('submit_requisition', 'تقديم طلب شراء للموافقة'), ('convert_requisition', 'تحويل طلب الشراء لمرحلة لاحقة'), ('cancel_requisition', 'إلغاء طلب شراء')],
            },
        ),
        migrations.CreateModel(
            name='RequisitionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='السعر التقديري للوحدة')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوريد المطلوب')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='requisitions.requisition', verbose_name='طلب الشراء')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.unitofmeasure', verbose_name='وحدة القياس')),
            ],
            options={
                'verbose_name': 'بند طلب شراء',
                'verbose_name_plural': 'بنود طلب الشراء',
                'ordering': ['id'],
            },
        ),
    ]
