# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('audit', '0001_initial'), ('audit', '0002_alter_auditlog_action_alter_auditlog_model_name_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'دخول'), ('export', 'تصدير'), ('import', 'استيراد'), ('post', 'ترحيل'), ('reverse', 'عكس'), ('backup', 'نسخ احتياطي'), ('sync', 'مزامنة')], db_index=True, max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='النموذج')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='معرف السجل')),
                ('object_repr', models.CharField(max_length=200, verbose_name='وصف السجل')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='المتصفح')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ والوقت')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'action'], name='audit_model_action_idx')],
            },
        ),
    ]
