# Generated by Django 4.2.30 on 2026-07-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial_squashed_0002_alter_auditlog_action_alter_auditlog_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'دخول'), ('export', 'تصدير'), ('import', 'استيراد'), ('post', 'ترحيل'), ('reverse', 'عكس'), ('backup', 'نسخ احتياطي'), ('sync', 'مزامنة'), ('access_denied', 'رفض وصول'), ('permission_change', 'تغيير صلاحية')], db_index=True, max_length=20, verbose_name='الإجراء'),
        ),
    ]
