# Generated by Django 4.2.30 on 2026-07-15 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_cogs_account_company_customer_account_and_more'),
        ('warehouses', '0001_initial_squashed_0003_stockmovement_sm_wh_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial_squashed_0007_alter_journalentryline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدور')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الدور')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_system', models.BooleanField(default=False, help_text='الأدوار النظامية جاهزة ولا يمكن حذفها', verbose_name='دور نظامي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دور',
                'verbose_name_plural': 'الأدوار',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='مثل: sales.invoice', max_length=100, unique=True, verbose_name='كود الشاشة')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الشاشة')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='الوحدة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شاشة',
                'verbose_name_plural': 'الشاشات',
                'ordering': ['module', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_receive', models.BooleanField(default=False, verbose_name='استلام')),
                ('can_issue', models.BooleanField(default=False, verbose_name='صرف')),
                ('can_count', models.BooleanField(default=False, verbose_name='جرد')),
                ('can_transfer', models.BooleanField(default=False, verbose_name='تحويل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'مخزن مخوّل',
                'verbose_name_plural': 'المخازن المخوّلة',
                'unique_together': {('user', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='UserScreenPermission',
            fields=[
                ('can_view', models.BooleanField(default=False, verbose_name='مشاهدة')),
                ('can_add', models.BooleanField(default=False, verbose_name='إضافة')),
                ('can_edit', models.BooleanField(default=False, verbose_name='تعديل')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('can_print', models.BooleanField(default=False, verbose_name='طباعة')),
                ('can_export', models.BooleanField(default=False, verbose_name='تصدير')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('allow', 'سماح'), ('deny', 'حرمان صريح')], default='allow', max_length=10, verbose_name='نوع المنح')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='access_control.screen', verbose_name='الشاشة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'استثناء صلاحية مستخدم',
                'verbose_name_plural': 'استثناءات صلاحيات المستخدمين',
                'unique_together': {('user', 'screen')},
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='مُنِح بواسطة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='access_control.role', verbose_name='الدور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إسناد دور',
                'verbose_name_plural': 'إسنادات الأدوار',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='UserBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False, verbose_name='الفرع الافتراضي')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='company.companybranch', verbose_name='الفرع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_branches', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'فرع مخوّل',
                'verbose_name_plural': 'الفروع المخوّلة',
                'unique_together': {('user', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='UserAccountTypeScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=True, verbose_name='مشاهدة')),
                ('can_transact', models.BooleanField(default=False, verbose_name='إجراء حركات')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_users', to='accounts.accounttype', verbose_name='نوع الحساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_account_types', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نطاق نوع حساب',
                'verbose_name_plural': 'نطاقات أنواع الحسابات',
                'unique_together': {('user', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='RoleScreenPermission',
            fields=[
                ('can_view', models.BooleanField(default=False, verbose_name='مشاهدة')),
                ('can_add', models.BooleanField(default=False, verbose_name='إضافة')),
                ('can_edit', models.BooleanField(default=False, verbose_name='تعديل')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('can_print', models.BooleanField(default=False, verbose_name='طباعة')),
                ('can_export', models.BooleanField(default=False, verbose_name='تصدير')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(choices=[('allow', 'سماح'), ('deny', 'حرمان صريح')], default='allow', max_length=10, verbose_name='نوع المنح')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_permissions', to='access_control.role', verbose_name='الدور')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='access_control.screen', verbose_name='الشاشة')),
            ],
            options={
                'verbose_name': 'صلاحية دور على شاشة',
                'verbose_name_plural': 'صلاحيات الأدوار على الشاشات',
                'unique_together': {('role', 'screen')},
            },
        ),
    ]
