# Generated by Django 4.2.30 on 2026-07-14 10:18

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('treasury', '0001_initial'), ('treasury', '0002_alter_bank_options'), ('treasury', '0003_banktransaction_bt_date_idx_and_more'), ('treasury', '0004_alter_bank_is_active_alter_banktransaction_amount_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('branch', models.CharField(blank=True, max_length=200, null=True, verbose_name='الفرع')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الآيبان')),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='الكود السويفت')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
                'ordering': ['name'],
                'permissions': [('approve_banktransaction', 'اعتماد معاملة بنكية'), ('print_banktransaction', 'طباعة معاملة بنكية'), ('export_banktransaction', 'تصدير المعاملات البنكية')],
            },
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخزينة')),
                ('responsible_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='المسئول')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('maximum_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الحد الأقصى')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'خزينة',
                'verbose_name_plural': 'الخزائن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('transfer_in', 'تحويل وارد'), ('transfer_out', 'تحويل صادر'), ('check_in', 'إيداع شيك'), ('check_out', 'صرف شيك')], max_length=20, verbose_name='نوع المعاملة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد بعد المعاملة')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('check_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشيك')),
                ('description', models.TextField(verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.bank', verbose_name='البنك')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'معاملة بنكية',
                'verbose_name_plural': 'المعاملات البنكية',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='bt_date_idx'), models.Index(fields=['bank', '-date'], name='bt_bank_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'إيداع'), ('withdrawal', 'سحب'), ('transfer', 'تحويل')], max_length=20, verbose_name='نوع المعاملة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد بعد المعاملة')),
                ('description', models.TextField(verbose_name='البيان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.safe', verbose_name='الخزينة')),
            ],
            options={
                'verbose_name': 'معاملة خزينة',
                'verbose_name_plural': 'معاملات الخزائن',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='st_date_idx'), models.Index(fields=['safe', '-date'], name='st_safe_date_idx')],
            },
        ),
    ]
