# Generated by Django 4.2.30 on 2026-07-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0007_alter_journalentryline_options_and_more'),
        ('treasury', '0001_initial_squashed_0004_alter_bank_is_active_alter_banktransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='counterparty_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_tx_counterparty', to='accounts.account', verbose_name='حساب الطرف المقابل'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='مرحل للاستاذ العام'),
        ),
        migrations.AddField(
            model_name='safetransaction',
            name='counterparty_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safe_tx_counterparty', to='accounts.account', verbose_name='حساب الطرف المقابل'),
        ),
        migrations.AddField(
            model_name='safetransaction',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='مرحل للاستاذ العام'),
        ),
    ]
