# Generated by Django 4.2.30 on 2026-07-20 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_banktransaction_counterparty_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='safetransaction',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='التاريخ'),
        ),
    ]
