# Generated by Django 4.2.30 on 2026-07-12 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], max_length=20, verbose_name='التكرار')),
                ('day_of_month', models.IntegerField(default=1, verbose_name='يوم الشهر')),
                ('next_due_date', models.DateField(verbose_name='التاريخ التالي')),
                ('journal_type', models.CharField(choices=[('general', 'قيد عام'), ('receipt', 'قبض'), ('payment', 'صرف')], default='general', max_length=20, verbose_name='نوع القيد')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='المرجع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('paused', 'متوقف'), ('completed', 'مكتمل')], default='active', max_length=20, verbose_name='الحالة')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المدين')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الدائن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'قيد دوري',
                'verbose_name_plural': 'قيود دورية',
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_date', models.DateField(verbose_name='تاريخ التنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='recurring.recurringjournal', verbose_name='القيد')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المرتبط')),
            ],
            options={
                'verbose_name': 'سجل تنفيذ قيد دوري',
                'verbose_name_plural': 'سجلات تنفيذ القيود الدورية',
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='البيان')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الدائن')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='recurring.recurringjournal', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'بند قيد دوري',
                'verbose_name_plural': 'بنود قيد دوري',
            },
        ),
    ]
