# Generated by Django 4.2.30 on 2026-07-11 21:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='مصر', max_length=100, verbose_name='الدولة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='المحمول')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='الفاكس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('company_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company logos/', verbose_name='شعار الشركة')),
                ('currency', models.CharField(default='ج.م', max_length=10, verbose_name='العملة')),
                ('currency_code', models.CharField(default='EGP', max_length=10, verbose_name='كود العملة')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة VAT %')),
                ('fiscal_year_start', models.CharField(default='01-01', max_length=5, verbose_name='بداية السنة المالية')),
                ('fiscal_year_end', models.CharField(default='12-31', max_length=5, verbose_name='نهاية السنة المالية')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='اسم البنك')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب البنكي')),
                ('bank_iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('bank_swift', models.CharField(blank=True, max_length=20, verbose_name='SWIFT Code')),
                ('registration_notes', models.TextField(blank=True, verbose_name='ملاحظات التسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الشركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='المدير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_default', models.BooleanField(default=False, verbose_name='الفرع الرئيسي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
    ]
