# Generated by Django 4.2.30 on 2026-07-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_current_balance_and_more"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب تكلفة البضاعة المباعة",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="customer_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب العملاء الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب المخزون",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="purchases_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب المشتريات",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="sales_revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب إيرادات المبيعات",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="supplier_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب الموردين الافتراضي",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="vat_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب ضريبة القيمة المضافة",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="withholding_tax_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.account",
                verbose_name="حساب الخصم والتحصيل",
            ),
        ),
    ]
