# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('cheques', '0001_initial'), ('cheques', '0002_alter_cheque_status')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('sales', '0002_salesinvoice_withholding_tax_amount_and_more'),
        ('purchases', '0002_purchaseinvoice_withholding_tax_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cheque_number', models.CharField(max_length=50, verbose_name='رقم الشيك')),
                ('cheque_type', models.CharField(choices=[('received', 'شيك وارد'), ('issued', 'شيك صادر')], max_length=10, verbose_name='نوع الشيك')),
                ('bank_name', models.CharField(max_length=100, verbose_name='البنك')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='الفرع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='العملة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('payee_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='المستفيد/الدافع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('deposited', 'ودع في البنك'), ('cleared', 'محصل'), ('bounced', 'مرتجع'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=15, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='accounts.account', verbose_name='الحساب البنكي')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='العميل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='فاتورة مبيعات')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseinvoice', verbose_name='فاتورة مشتريات')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'شيك',
                'verbose_name_plural': 'الشيكات',
                'ordering': ['-due_date'],
            },
        ),
    ]
