# Generated by Django 4.2.30 on 2026-07-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0007_alter_journalentryline_options_and_more'),
        ('cheques', '0001_initial_squashed_0002_alter_cheque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_gl_entries', to='accounts.account', verbose_name='حساب الشيكات المحاسبي'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي'),
        ),
    ]
