# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('warehouses', '0001_initial'), ('warehouses', '0002_alter_stockmovement_options_and_more'), ('warehouses', '0003_stockmovement_sm_wh_date_idx_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
        ('purchases', '0010_alter_supplier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المخزن')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المخزن')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='الموقع')),
                ('manager', models.CharField(blank=True, max_length=200, null=True, verbose_name='مدير المخزن')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='التليفون')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية الحالية')),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى')),
                ('maximum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأقصى')),
                ('last_count_date', models.DateField(blank=True, null=True, verbose_name='آخر جرد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stock', to='purchases.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'منتج في المخزن',
                'verbose_name_plural': 'منتجات المخازن',
                'ordering': ['warehouse', 'product'],
                'unique_together': {('warehouse', 'product')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الحركة')),
                ('movement_type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر'), ('transfer', 'تحويل'), ('adjustment', 'تسوية'), ('return_in', 'مرتجع وارد'), ('return_out', 'مرتجع صادر')], max_length=20, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='التكلفة الإجمالية')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نفّذ الحركة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='purchases.product', verbose_name='المنتج')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='warehouses.warehouse', verbose_name='المخزن المحول إليه')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'حركة مخزون',
                'verbose_name_plural': 'حركات المخزون',
                'ordering': ['-date', '-created_at'],
                'permissions': [('export_stockmovement', 'تصدير حركات المخزون')],
                'indexes': [models.Index(fields=['warehouse', '-date'], name='sm_wh_date_idx'), models.Index(fields=['product', '-date'], name='sm_prod_date_idx'), models.Index(fields=['movement_type', '-date'], name='sm_type_date_idx')],
            },
        ),
    ]
