# Generated by Django 4.2.30 on 2026-07-19 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0013_alter_purchaseinvoice_options_and_more'),
        ('warehouses', '0001_initial_squashed_0003_stockmovement_sm_wh_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('quantity_remaining', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الكمية المتبقية')),
                ('unit_cost', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='التكلفة الإجمالية')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='purchases.product', verbose_name='المنتج')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='warehouses.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'طبقة تكلفة مخزون',
                'verbose_name_plural': 'طبقات تكلفة المخزون',
                'ordering': ['date', 'created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'is_active'], name='icl_prod_wh_idx')],
            },
        ),
    ]
