# Generated by Django 4.2.30 on 2026-07-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('contractors', '0001_initial'), ('contractors', '0002_alter_interimcertificate_options')]

    dependencies = [
        ('treasury', '0001_initial'),
        ('accounts', '0005_alter_account_current_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان العقد')),
                ('contract_type', models.CharField(choices=[('lump_sum', 'مبلغ مقطوع'), ('unit_price', 'أسعارunità'), ('cost_plus', 'التكلفة + ربح'), ('time_material', 'وقت + مواد')], default='lump_sum', max_length=20, verbose_name='نوع العقد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'قيد الموافقة'), ('active', 'نشط'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('closed', 'مغلق'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('contract_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='قيمة العقد')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=14, max_digits=5, verbose_name='نسبة الضريبة')),
                ('vat_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='مبلغ الضريبة')),
                ('total_with_vat', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الإجمالي شامل الضريبة')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية الفعلي')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='نسبة الاحتفاظ')),
                ('advance_payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الدفعة المقدمة')),
                ('advance_payment_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='قيمة الدفعة المقدمة')),
                ('penalties_clause', models.TextField(blank=True, verbose_name='شروط الغرامات')),
                ('special_conditions', models.TextField(blank=True, verbose_name='شروط خاصة')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الإنجاز')),
                ('total_certified', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='إجمالي المستخلصات')),
                ('total_paid', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='إجمالي المدفوعات')),
                ('total_retained', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='إجمالي المحتجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterimCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='رقم المستخلص')),
                ('period_number', models.PositiveIntegerField(help_text='رقم الفترة الزمنية', verbose_name='فترة المستخلص')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('approved', 'موافق عليه'), ('certified', 'معتمد'), ('paid', 'مدفوع'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='الحالة')),
                ('gross_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='المبلغ الإجمالي')),
                ('previous_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='المبلغ السابق')),
                ('current_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='المبلغ الحالي')),
                ('retention_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='مبلغ الاحتفاظ')),
                ('advance_deduction', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='خصم الدفعة المقدمة')),
                ('vat_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الضريبة')),
                ('net_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='المبلغ الصافي')),
                ('paid_amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='المبلغ المدفوع')),
                ('period_from', models.DateField(verbose_name='من تاريخ')),
                ('period_to', models.DateField(verbose_name='إلى تاريخ')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='contractors.contract', verbose_name='العقد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
            ],
            options={
                'verbose_name': 'مستخلص',
                'verbose_name_plural': 'المستخلصات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الدفعة')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('check', 'شيك'), ('advance', 'دفعة مقدمة'), ('retention_release', 'إفراج عن محتجز')], default='bank_transfer', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('check_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الشيك')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع التحويل')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('paid', 'مدفوع'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contractors.interimcertificate', verbose_name='المستخلص المرتبط')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contractors.contract', verbose_name='العقد')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
                ('safe_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treasury.safetransaction', verbose_name='حركة الخزينة')),
            ],
            options={
                'verbose_name': 'دفعة مقاول',
                'verbose_name_plural': 'مدفوعات المقاولين',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود المقاول')),
                ('name', models.CharField(max_length=300, verbose_name='اسم المقاول')),
                ('contractor_type', models.CharField(choices=[('company', 'شركة'), ('individual', 'فرد'), ('government', 'جهة حكومية')], default='company', max_length=20, verbose_name='النوع')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='رقم السجل التجاري')),
                ('phone', models.CharField(max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('speciality', models.CharField(blank=True, help_text='مثال: أعمال هيكلية، كهرباء، سباكة', max_length=200, verbose_name='التخصص')),
                ('credit_limit', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='حد الائتمان')),
                ('current_balance', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الرصيد الحالي')),
                ('retention_rate', models.DecimalField(decimal_places=2, default=5, help_text='نسبة الاحتفاظ من كل مستخلص %', max_digits=5, verbose_name='نسبة الاحتفاظ')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'معلق'), ('blacklisted', 'محظور')], default='active', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('account', models.ForeignKey(blank=True, help_text='حساب المقاول في دليل الحسابات', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'مقاول',
                'verbose_name_plural': 'المقاولون',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.CharField(max_length=20, verbose_name='رقم البند')),
                ('description', models.TextField(verbose_name='وصف البند')),
                ('unit', models.CharField(default='م³', max_length=50, verbose_name='الوحدة')),
                ('quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي')),
                ('executed_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الكمية المنفذة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contractors.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'بند العقد',
                'verbose_name_plural': 'بنود العقد',
                'ordering': ['order', 'item_number'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contractors.contractor', verbose_name='المقاول'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cost_account',
            field=models.ForeignKey(blank=True, help_text='حساب تكلفة الأعمال في دليل الحسابات', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='حساب تكاليف العقد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.CreateModel(
            name='CertificateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الكمية السابقة')),
                ('current_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الكمية الحالية')),
                ('total_executed', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الإجمالي المنفذ')),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='المبلغ')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contractors.interimcertificate', verbose_name='المستخلص')),
                ('contract_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_items', to='contractors.contractitem', verbose_name='بند العقد')),
            ],
            options={
                'verbose_name': 'بند مستخلص',
                'verbose_name_plural': 'بنود المستخلص',
                'ordering': ['contract_item__order'],
            },
        ),
        migrations.AddIndex(
            model_name='interimcertificate',
            index=models.Index(fields=['status'], name='contractors_status_368b24_idx'),
        ),
        migrations.AddIndex(
            model_name='interimcertificate',
            index=models.Index(fields=['contract'], name='contractors_contrac_799601_idx'),
        ),
        migrations.AddIndex(
            model_name='interimcertificate',
            index=models.Index(fields=['-created_at'], name='contractors_created_3ff79c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorpayment',
            index=models.Index(fields=['status'], name='contractors_status_45ec9b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorpayment',
            index=models.Index(fields=['contract'], name='contractors_contrac_09cada_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorpayment',
            index=models.Index(fields=['-payment_date'], name='contractors_payment_0ae906_idx'),
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['status'], name='contractors_status_945287_idx'),
        ),
        migrations.AddIndex(
            model_name='contractor',
            index=models.Index(fields=['code'], name='contractors_code_c29924_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contractors_status_5f14b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contractor'], name='contractors_contrac_493114_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-created_at'], name='contractors_created_f7b072_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='contractors_start_d_ca0af1_idx'),
        ),
        migrations.AlterModelOptions(
            name='interimcertificate',
            options={'ordering': ['-created_at'], 'permissions': [('approve_interimcertificate', 'اعتماد مستخلص'), ('print_interimcertificate', 'طباعة مستخلص'), ('export_interimcertificate', 'تصدير المستخلصات')], 'verbose_name': 'مستخلص', 'verbose_name_plural': 'المستخلصات'},
        ),
    ]
