# Generated by Django 4.2.30 on 2026-07-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('purchases', '0013_alter_purchaseinvoice_options_and_more'),
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ الاستلام')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'عرض سعر مورد',
                'verbose_name_plural': 'عروض أسعار الموردين',
                'ordering': ['-received_date', '-created_at'],
                'permissions': [('accept_quotation', 'قبول عرض السعر'), ('reject_quotation', 'رفض عرض السعر')],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسل'), ('closed', 'مغلق'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.costcenter', verbose_name='مركز التكلفة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_requested', to=settings.AUTH_USER_MODEL, verbose_name='طالب الشراء')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='requisitions.requisition', verbose_name='الطلب الداخلي')),
            ],
            options={
                'verbose_name': 'طلب عروض أسعار',
                'verbose_name_plural': 'طلبات عروض الأسعار',
                'ordering': ['-date', '-number'],
                'permissions': [('approve_rfq', 'اعتماد طلب عروض أسعار'), ('send_rfq', 'إرسال طلب عروض أسعار'), ('close_rfq', 'إغلاق طلب عروض أسعار'), ('convert_rfq', 'تحويل طلب عروض أسعار إلى أمر شراء')],
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوريد المطلوب')),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='السعر التقديري')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف إضافي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rfq.rfq', verbose_name='طلب عروض الأسعار')),
            ],
            options={
                'verbose_name': 'بند طلب عرض السعر',
                'verbose_name_plural': 'بنود طلب عروض الأسعار',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='سعر الوحدة')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الخصم')),
                ('delivery_days', models.IntegerField(blank=True, null=True, verbose_name='أيام التسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rfq.quotation', verbose_name='عرض السعر')),
                ('rfq_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_lines', to='rfq.rfqline', verbose_name='بند الطلب')),
            ],
            options={
                'verbose_name': 'بند عرض السعر',
                'verbose_name_plural': 'بنود عروض الأسعار',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='rfq.rfq', verbose_name='طلب عروض الأسعار'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد'),
        ),
    ]
