# Generated by Django 4.2.30 on 2026-07-14 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('credit_notes', '0001_initial'), ('credit_notes', '0002_creditnote_journal_entry'), ('credit_notes', '0003_creditnote_original_purchase_invoice_and_more')]

    dependencies = [
        ('sales', '0002_salesinvoice_withholding_tax_amount_and_more'),
        ('purchases', '0002_purchaseinvoice_withholding_tax_amount_and_more'),
        ('purchases', '0009_alter_purchaseinvoice_discount_amount_and_more'),
        ('accounts', '0004_alter_account_current_balance_and_more'),
        ('sales', '0006_alter_salesinvoice_cost_of_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('credit_note', 'إشعار دائن (مرتجع مبيعات)'), ('debit_note', 'إشعار مدين (مرتجع مشتريات)')], max_length=20, verbose_name='النوع')),
                ('note_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإشعار')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('original_invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة الأصلية')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الإجمالي')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الإشعار')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='العميل')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='المورد')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
                ('original_purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseinvoice', verbose_name='فاتورة المشتريات الأصلية')),
                ('original_sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='فاتورة المبيعات الأصلية')),
            ],
            options={
                'verbose_name': 'إشعار مدين/دائن',
                'verbose_name_plural': 'إشعارات المدين والدائن',
                'ordering': ['-date'],
            },
        ),
    ]
