# Generated by Django 4.2.30 on 2026-07-20 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_notes', '0001_initial_squashed_0003_creditnote_original_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='التاريخ'),
        ),
    ]
