# Generated by Django 4.2.30 on 2026-07-11 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فئة الإشعار',
                'verbose_name_plural': 'فئات الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('event', models.CharField(choices=[('invoice_created', 'إنشاء فاتورة'), ('invoice_posted', 'ترحيل فاتورة'), ('invoice_overdue', 'فاتورة متأخرة'), ('low_stock', 'مخزون منخفض'), ('salary_due', 'موعد صرف رواتب'), ('backup_completed', 'اكتمال النسخ الاحتياطي'), ('reconciliation_needed', 'حاجة تسوية بنكية'), ('document_expiring', 'وثيقة تنتهي صلاحيتها')], max_length=50, unique=True, verbose_name='الحدث')),
                ('subject_template', models.CharField(max_length=200, verbose_name='قالب الموضوع')),
                ('body_template', models.TextField(verbose_name='قالب المحتوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('recipients', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='المستلمون')),
            ],
            options={
                'verbose_name': 'قالب إشعار',
                'verbose_name_plural': 'قوالب الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='البريد للمستلم')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True, verbose_name='نجاح')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate', verbose_name='القالب')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجلات الإشعارات',
                'ordering': ['-sent_at'],
            },
        ),
    ]
