# Generated by Django 4.2.30 on 2026-07-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event',
            field=models.CharField(choices=[('invoice_created', 'إنشاء فاتورة مبيعات'), ('invoice_posted', 'ترحيل فاتورة مبيعات'), ('invoice_overdue', 'فاتورة مبيعات متأخرة'), ('low_stock', 'مخزون منخفض'), ('salary_due', 'موعد صرف رواتب'), ('backup_completed', 'اكتمال النسخ الاحتياطي'), ('reconciliation_needed', 'حاجة تسوية بنكية'), ('document_expiring', 'وثيقة تنتهي صلاحيتها'), ('purchase_invoice_created', 'إنشاء فاتورة مشتريات'), ('purchase_invoice_posted', 'ترحيل فاتورة مشتريات'), ('contractor_payment_created', 'إنشاء دفعة مقاول'), ('contractor_payment_posted', 'ترحيل دفعة مقاول'), ('supplier_credit_exceeded', 'تجاوز حد ائتمان المورد')], max_length=50, unique=True, verbose_name='الحدث'),
        ),
    ]
