# Generated by Django 4.2.30 on 2026-07-14 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0012_alter_supplier_credit_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم أمر الشراء')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسل'), ('approved', 'معتمد'), ('received', 'مستلم'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-date', '-order_number'],
                'permissions': [('approve_purchaseorder', 'اعتماد أمر شراء'), ('cancel_purchaseorder', 'إلغاء أمر شراء'), ('convert_purchaseorder', 'تحويل أمر شراء إلى فاتورة')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='سعر الوحدة')),
                ('received_quantity', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الكمية المستلمة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase_orders.purchaseorder', verbose_name='أمر الشراء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند أمر شراء',
                'verbose_name_plural': 'بنود أمر الشراء',
                'ordering': ['id'],
            },
        ),
    ]
