# Generated by Django 4.2.30 on 2026-07-19 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_create_standard_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0013_alter_purchaseinvoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العرض')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('valid_until', models.DateField(verbose_name='صالح حتى')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسلة'), ('accepted', 'مقبولة'), ('rejected', 'مرفوضة'), ('expired', 'منتهية الصلاحية'), ('converted', 'محولة لفاتورة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='شروط الدفع')),
                ('delivery_terms', models.CharField(blank=True, max_length=200, verbose_name='شروط التسليم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('subtotal', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي قبل الضريبة')),
                ('vat_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice', verbose_name='الفاتورة المحولة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'عرض سعر مبيعات',
                'verbose_name_plural': 'عروض أسعار المبيعات',
                'ordering': ['-date', '-quotation_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('total_price', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales_quotation.salesquotation', verbose_name='العرض')),
            ],
            options={
                'verbose_name': 'بند عرض سعر',
                'verbose_name_plural': 'بنود عروض الأسعار',
                'ordering': ['id'],
            },
        ),
    ]
