# Generated by Django 4.2.30 on 2026-07-14 10:03

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('sales', '0001_initial'), ('sales', '0002_salesinvoice_withholding_tax_amount_and_more'), ('sales', '0003_salesinvoice_file_number'), ('sales', '0004_alter_salesinvoice_cost_of_goods_and_more'), ('sales', '0005_salesinvoice_si_customer_date_idx_and_more'), ('sales', '0006_alter_salesinvoice_cost_of_goods_and_more'), ('sales', '0007_alter_salesinvoice_options'), ('sales', '0008_salesinvoice_production_order'), ('sales', '0009_salesinvoice_branch'), ('sales', '0010_alter_customer_credit_limit_and_more')]

    dependencies = [
        ('purchases', '0001_initial_squashed_0011_alter_supplier_credit_limit_and_more'),
        ('company', '0002_company_cogs_account_company_customer_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial_squashed_0007_alter_journalentryline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود العميل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_type', models.CharField(choices=[('company', 'شركة'), ('individual', 'فرد'), ('government', 'جهة حكومية')], default='company', max_length=20, verbose_name='نوع العميل')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, null=True, verbose_name='سجل تجاري')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='التليفون')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='المحمول')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='حد الائتمان')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='الحساب المحاسبي')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('check', 'شيك'), ('transfer', 'تحويل بنكي')], default='credit', max_length=20, verbose_name='طريقة الدفع')),
                ('is_tax_invoice', models.BooleanField(default=True, verbose_name='فاتورة مؤثرة في الضرائب')),
                ('subtotal', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ قبل الضريبة')),
                ('vat_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='ضريبة القيمة المضافة')),
                ('discount_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الخصم على الفاتورة')),
                ('total_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ المحصّل')),
                ('remaining_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ المتبقي')),
                ('cost_of_goods', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='تكلفة البضاعة')),
                ('gross_profit', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='إجمالي الربح')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer', verbose_name='العميل')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.journalentry', verbose_name='القيد المحاسبي')),
                ('withholding_tax_amount', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='مبلغ الخصم والتحصيل')),
                ('withholding_tax_type', models.IntegerField(choices=[(0, 'بدون'), (1, '1% - شركات'), (3, '3% - جهات حكومية'), (5, '5% - مقاولات')], default=0, verbose_name='نسبة الخصم والتحصيل')),
                ('file_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الملف')),
            ],
            options={
                'verbose_name': 'فاتورة مبيعات',
                'verbose_name_plural': 'فواتير المبيعات',
                'ordering': ['-date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='سعر البيع')),
                ('cost_price', models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='سعر الشراء')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('total_price', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الإجمالي')),
                ('cost_total', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='التكلفة')),
                ('profit', models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='الربح')),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الربح %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند فاتورة مبيعات',
                'verbose_name_plural': 'بنود فواتير المبيعات',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['customer', '-date'], name='si_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['date', 'is_posted'], name='si_date_posted_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['invoice_number'], name='si_number_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['file_number'], name='si_file_number_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['payment_method', '-date'], name='si_paymethod_date_idx'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='cost_of_goods',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='تكلفة البضاعة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='الخصم على الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='gross_profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='إجمالي الربح'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ المحصّل'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل'), ('check', 'شيك'), ('transfer', 'تحويل بنكي')], default='credit', max_length=20, validators=[common.validators.validate_payment_method], verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='المبلغ قبل الضريبة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='ضريبة القيمة المضافة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='مبلغ الخصم والتحصيل'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='withholding_tax_type',
            field=models.IntegerField(choices=[(0, 'بدون'), (1, '1% - شركات'), (3, '3% - جهات حكومية'), (5, '5% - مقاولات')], default=0, validators=[common.validators.validate_withholding_tax_type], verbose_name='نسبة الخصم والتحصيل'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='cost_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='سعر الشراء'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='cost_total',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='التكلفة'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[common.validators.validate_positive_decimal], verbose_name='نسبة الخصم'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='الربح'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_positive_decimal], verbose_name='الإجمالي'),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[common.validators.validate_positive_decimal], verbose_name='سعر البيع'),
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-date', '-invoice_number'], 'permissions': [('approve_salesinvoice', 'اعتماد فاتورة مبيعات'), ('print_salesinvoice', 'طباعة فاتورة مبيعات'), ('export_salesinvoice', 'تصدير فواتير المبيعات')], 'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
    ]
