# Generated by Django 4.2.30 on 2026-07-14 12:28

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_production_order_and_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='حد الائتمان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_non_negative_decimal], verbose_name='الخصم على الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, validators=[common.validators.validate_non_negative_decimal], verbose_name='المبلغ المحصّل'),
        ),
    ]
