# Generated by Django 4.2.30 on 2026-07-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
        ('sales', '0005_create_standard_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currency.currency', verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='currency_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='المبلغ بالعملة'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=15, verbose_name='سعر الصرف'),
        ),
    ]
