# Generated by Django 4.2.30 on 2026-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_salesinvoice_currency_salesinvoice_currency_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(
                blank=True,
                default="EG",
                max_length=100,
                null=True,
                verbose_name="الدولة",
            ),
        ),
    ]
