# -*- mode: python ; coding: utf-8 -*-
import os
import sys
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

block_cipher = None

project_root = os.path.abspath(SPECPATH)

a = Analysis(
    [os.path.join(project_root, 'manage.py')],
    pathex=[project_root],
    binaries=[],
    datas=[
        (os.path.join(project_root, 'templates'), 'templates'),
        (os.path.join(project_root, 'static'), 'static'),
        (os.path.join(project_root, 'accounting_system'), 'accounting_system'),
        (os.path.join(project_root, 'accounts'), 'accounts'),
        (os.path.join(project_root, 'sales'), 'sales'),
        (os.path.join(project_root, 'purchases'), 'purchases'),
        (os.path.join(project_root, 'treasury'), 'treasury'),
        (os.path.join(project_root, 'assets'), 'assets'),
        (os.path.join(project_root, 'hr'), 'hr'),
        (os.path.join(project_root, 'reports'), 'reports'),
        (os.path.join(project_root, 'documents'), 'documents'),
        (os.path.join(project_root, 'warehouses'), 'warehouses'),
        (os.path.join(project_root, 'company'), 'company'),
        (os.path.join(project_root, 'ai_analysis'), 'ai_analysis'),
        (os.path.join(project_root, 'backups'), 'backups'),
        (os.path.join(project_root, 'sync'), 'sync'),
        (os.path.join(project_root, 'common'), 'common'),
    ],
    hiddenimports=[
        'django',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.contrib.humanize',
        'crispy_forms',
        'crispy_bootstrap5',
        'jazzmin',
        'accounts',
        'accounts.models',
        'accounts.views',
        'accounts.urls',
        'purchases',
        'purchases.models',
        'purchases.views',
        'purchases.urls',
        'sales',
        'sales.models',
        'sales.views',
        'sales.urls',
        'treasury',
        'treasury.models',
        'treasury.views',
        'treasury.urls',
        'assets',
        'assets.models',
        'assets.views',
        'assets.urls',
        'hr',
        'hr.models',
        'hr.views',
        'hr.urls',
        'reports',
        'reports.models',
        'reports.views',
        'reports.urls',
        'documents',
        'documents.models',
        'documents.views',
        'documents.urls',
        'warehouses',
        'warehouses.models',
        'warehouses.views',
        'warehouses.urls',
        'company',
        'company.models',
        'company.views',
        'company.urls',
        'company.context_processors',
        'ai_analysis',
        'ai_analysis.models',
        'ai_analysis.views',
        'ai_analysis.urls',
        'backups',
        'backups.models',
        'backups.views',
        'backups.urls',
        'sync',
        'sync.models',
        'sync.views',
        'sync.urls',
        'sync.sync_engine',
        'common',
        'common.excel_utils',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AccountingSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AccountingSystem',
)
